spring.application.name=solace-project
server.port=8081

app.solace.booking-queue=flight.booking.queue

app.features.publish-bookings-to-solace=true
app.features.auto-confirm-bookings=true
app.features.booking-history=true

solace.jms.host=${SOLACE_JMS_HOST:smf://localhost:55554}
solace.jms.msgVpn=${SOLACE_JMS_MSG_VPN:default}
solace.jms.clientUsername=${SOLACE_JMS_CLIENT_USERNAME:default}
solace.jms.clientPassword=${SOLACE_JMS_CLIENT_PASSWORD:default}
solace.jms.apiProperties.Solace_JMS_DynamicDurables=true

management.endpoints.web.exposure.include=health,info
spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/your_database_name?authSource=admin

