app.features.publish-bookings-to-solace=true
app.features.auto-confirm-bookings=true
app.features.booking-history=true

spring.jms.listener.auto-startup=true
spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/your_database_name?authSource=admin
# --- GIT_LEAKS_TEST_START ---
# AWS Credentials
aws.access.key.id=AKIAIOSFODNN7EXAMPLE
aws.secret.access.key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

# Database Credentials
spring.datasource.password=db_password123!
app.db.secret=am9objpkb2U=

# Third-Party API Keys
stripe.api.key=sk_live_51NxF2uL8yR7pZwQmNjK9vX
slack.webhook.url=https://slack.com
github.token=ghp_JgK8lM9N0oP1qR2sT3uV4wX5yZ6a7b8c9d0e
# --- GIT_LEAKS_TEST_END ---
