app.features.publish-bookings-to-solace=false
app.features.auto-confirm-bookings=false
app.features.booking-history=true

spring.jms.listener.auto-startup=false
spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/your_database_name?authSource=admin
