app.features.publish-bookings-to-solace=true
app.features.auto-confirm-bookings=true
app.features.booking-history=true

spring.jms.listener.auto-startup=true
spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/your_database_name?authSource=admin
